import type { ModuleDefinition } from '../types'

export const WEBSITE_MODULE: ModuleDefinition = {
  type: 'website',
  name: 'Website Audit',
  tagline: 'turn your website into a sales tool',
  description: 'Turns visitors into paying customers.',
  order: 2,
  unlockThreshold: 80,
  requirements: [
    {
      key: 'website_url',
      label: 'Your website URL',
      type: 'url',
      placeholder: 'yourdomain.com',
    },
  ],
  systemPrompt: `You are a senior growth consultant reviewing website audit findings. For each failing check, write 1–2 sentences explaining the business impact — why it matters for growth, conversions, or trust. Be specific to the site. Never generic.`,
  categories: [
    // ── 1. UX & UI ────────────────────────────────────────────────────────────
    {
      slug: 'ux',
      label: 'UX & UI',
      order: 1,
      subCategories: [
        {
          slug: 'ux-checks',
          label: 'Page Fundamentals',
          order: 1,
          items: [
            {
              slug: 'has-title',
              label: 'Title tag',
              prompt: 'Checked by rule engine — not used for Claude analysis.',
              order: 1,
              weight: 3,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'has-h1',
              label: 'H1 heading',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'viewport-meta',
              label: 'Mobile viewport tag',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 3,
              fixable: true,
              fixType: 'patch',
            },
          ],
        },
        {
          slug: 'accessibility-checks',
          label: 'Accessibility & WCAG',
          order: 2,
          items: [
            {
              slug: 'accessibility-score',
              label: 'Accessibility score',
              prompt: 'Checked by rule engine (Google Lighthouse accessibility audit).',
              order: 1,
              weight: 2,
              fixGuide: [
                'This score summarises every accessibility check Lighthouse ran on the page — fix the individual findings below (contrast, font size, tap targets, accessible names) and the score will rise automatically',
                'The checker below re-checks your live page automatically, so you can see the updated score right after you make a change — no need to manually re-run the audit',
              ],
            },
            {
              slug: 'color-contrast',
              label: 'Color contrast',
              prompt: 'Checked by rule engine (Google Lighthouse accessibility audit, WCAG 1.4.3).',
              order: 2,
              weight: 3,
              fixGuide: [
                'Find the low-contrast text — usually light gray text on a white/light background, or light text on a light-colored button',
                'Body text needs at least a 4.5:1 contrast ratio against its background; large text (18px+, or 14px+ bold) needs at least 3:1',
                'Use the contrast checker below to test your exact text and background colors before and after',
                'Darken the text color or lighten the background until the ratio passes — small adjustments are usually enough',
              ],
            },
            {
              slug: 'font-size',
              label: 'Legible font sizes',
              prompt: 'Checked by rule engine (Google Lighthouse SEO/mobile-friendliness audit).',
              order: 3,
              weight: 2,
              fixGuide: [
                'Set a base body font size of at least 16px in your CSS (e.g. html { font-size: 16px; })',
                'Avoid any text below 12px anywhere on the page, especially in footers, captions, and mobile nav menus',
                'Use the checker below to find the exact elements and font sizes that are too small on your live page',
                'Check the page on an actual mobile viewport (or Chrome DevTools device mode) — text that looks fine on desktop can be too small on mobile',
              ],
            },
            {
              slug: 'tap-targets',
              label: 'Tap target sizing',
              prompt: 'Checked by rule engine (Google Lighthouse audit, WCAG 2.5.5).',
              order: 4,
              weight: 2,
              fixGuide: [
                'Make every clickable button, link, and icon at least 48x48px on mobile — add padding if the visible icon/text is smaller',
                'Leave at least 8px of spacing between adjacent tap targets (e.g. social icons, nav items) so users don\'t mis-tap',
                'Pay special attention to mobile nav menus, footer links, and icon-only buttons — these are the most common offenders',
                'Use the checker below to find the exact undersized or overlapping tap targets on your live page',
              ],
            },
            {
              slug: 'accessible-names',
              label: 'Buttons & links have accessible names',
              prompt: 'Checked by rule engine (Google Lighthouse accessibility audit, WCAG 4.1.2).',
              order: 5,
              weight: 3,
              fixGuide: [
                'Icon-only buttons (hamburger menu, search, close, social icons) need an aria-label describing what they do, e.g. <button aria-label="Open menu">',
                'Links that only contain an image need alt text on the image, or an aria-label on the link itself',
                'Never leave a button or link with no visible text and no aria-label — screen reader users will hear nothing useful',
                'Use the checker below to find the exact buttons and links missing an accessible name on your live page',
              ],
            },
            {
              slug: 'heading-hierarchy',
              label: 'Heading hierarchy',
              prompt: 'Checked by rule engine (DOM heading order).',
              order: 6,
              weight: 2,
              fixGuide: [
                'Use exactly one <h1> per page for the main topic',
                'Nest headings in order — an <h2> can be followed by another <h2> or an <h3>, but never jump from <h2> straight to <h4>',
                'Screen reader users navigate by heading level, so a skipped level breaks the document outline',
              ],
            },
            {
              slug: 'skip-to-content',
              label: 'Skip-to-content link',
              prompt: 'Checked by rule engine (DOM parse).',
              order: 7,
              weight: 1,
              fixGuide: [
                'Add a link as the very first focusable element on the page that jumps to the main content',
                'Visually hide it by default, but make it visible when it receives keyboard focus',
                'This lets keyboard and screen reader users skip repeated nav/header content on every page load',
              ],
            },
          ],
        },
        {
          slug: 'accessibility-checks-advanced',
          label: 'Accessibility & WCAG (Browser-tested)',
          order: 3,
          items: [
            {
              slug: 'keyboard-nav-order',
              label: 'Keyboard tab order',
              prompt: 'Checked by real browser interaction (Playwright keyboard simulation).',
              order: 1,
              weight: 2,
              fixGuide: [
                'Tab through your page manually and confirm focus moves in a logical, visible order',
                'Never use a hidden element with a tabindex — it traps keyboard focus on something the user can\'t see',
                'Avoid positive tabindex values (tabindex="1", "2"...) — they override natural DOM order and usually cause more confusion than they fix',
              ],
            },
            {
              slug: 'focus-visible-states',
              label: 'Visible focus states',
              prompt: 'Checked by real browser interaction (computed style before/after focusing each element).',
              order: 2,
              weight: 2,
              fixGuide: [
                'Never use outline: none without replacing it with another visible focus style',
                'Add a clear outline or box-shadow on :focus-visible for every link, button, and form field',
                'Test by tabbing through the page — you should always be able to see where focus currently is',
              ],
            },
          ],
        },
      ],
    },

    // ── 2. Navigation & Structure ─────────────────────────────────────────────
    {
      slug: 'nav',
      label: 'Navigation & Structure',
      order: 2,
      subCategories: [
        {
          slug: 'nav-checks',
          label: 'Navigation',
          order: 1,
          items: [
            {
              slug: 'has-nav-landmark',
              label: 'Navigation structure',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 2,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'internal-links',
              label: 'Internal links',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
            },
            {
              slug: 'descriptive-link-text',
              label: 'Link anchor text',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 1,
            },
            {
              slug: 'external-link-safety',
              label: 'External link safety',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 1,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'breadcrumbs',
              label: 'Breadcrumb navigation',
              prompt: 'Checked by rule engine (DOM parse).',
              order: 5,
              weight: 1,
              fixGuide: [
                'Most useful on sites with pages more than 2 levels deep (e.g. Category > Subcategory > Product)',
                'Add a breadcrumb trail near the top of the page showing the path back to the homepage',
                'Include BreadcrumbList structured data so Google can show the trail in search results',
              ],
            },
            {
              slug: 'search-presence',
              label: 'Site search',
              prompt: 'Checked by rule engine (DOM parse).',
              order: 6,
              weight: 1,
              fixGuide: [
                'Most valuable for content-heavy sites — blogs, documentation, large product catalogs',
                'Add a search input in the header or nav that lets visitors find content directly',
                'Not essential for small marketing sites with only a handful of pages',
              ],
            },
            {
              slug: 'dead-links',
              label: 'Dead links',
              prompt: 'Checked by rule engine (HTTP status check on a sample of internal links).',
              order: 7,
              weight: 3,
              fixGuide: [
                'Broken internal links frustrate visitors and waste the SEO value of pages linking to them',
                'Check the specific links flagged below and either fix the URL or remove the link',
                'If a page was intentionally removed, redirect its old URL to the most relevant replacement page',
              ],
            },
            {
              slug: 'nav-label-clarity',
              label: 'Navigation label clarity',
              prompt: 'AI-assessed: are nav link labels clear and specific, or vague/internal jargon?',
              order: 8,
              weight: 2,
              fixGuide: [
                'Avoid vague single-word nav labels like "Solutions" or "Platform" with no context',
                'Use labels that tell a first-time visitor exactly what they will find on that page',
                'Test by asking someone unfamiliar with your product to guess what each nav item leads to',
              ],
            },
          ],
        },
        {
          slug: 'nav-checks-advanced',
          label: 'Navigation (Browser-tested)',
          order: 2,
          items: [
            {
              slug: 'mobile-nav-interaction',
              label: 'Mobile nav interaction',
              prompt: 'Checked by real browser interaction (Playwright taps the mobile menu button).',
              order: 1,
              weight: 2,
              fixGuide: [
                'Tap your mobile menu button on an actual phone (or Chrome DevTools device mode) and confirm the menu opens',
                'Make sure the button toggles aria-expanded="true"/"false" so screen readers announce the state change',
                'The menu should be reachable and closable by keyboard alone, not just touch',
              ],
            },
            {
              slug: 'mobile-nav-visual-quality',
              label: 'Mobile nav visual quality',
              prompt: 'AI-assessed (vision): does the mobile menu open cleanly, or does it look broken/overlapping?',
              order: 2,
              weight: 1,
              fixGuide: [
                'Check for overlapping content, cut-off text, or z-index issues when the menu opens',
                'The open/close animation should feel intentional, not glitchy',
                'Compare against the before/after screenshots the checker captured to see exactly what a visitor sees',
              ],
            },
          ],
        },
      ],
    },

    // ── 3. Page Speed ─────────────────────────────────────────────────────────
    {
      slug: 'speed',
      label: 'Page Speed',
      order: 3,
      subCategories: [
        {
          slug: 'speed-checks',
          label: 'Performance',
          order: 1,
          items: [
            {
              slug: 'response-time',
              label: 'Server response time',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 3,
            },
            {
              slug: 'page-size',
              label: 'Page file size',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
            },
            {
              slug: 'compression',
              label: 'Response compression',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 2,
            },
            {
              slug: 'image-dimensions',
              label: 'Image dimension attributes',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 1,
            },
            {
              slug: 'image-format-optimization',
              label: 'Modern image formats',
              prompt: 'Checked by rule engine (DOM parse of image file extensions).',
              order: 5,
              weight: 2,
              fixGuide: [
                'WebP and AVIF are typically 25-50% smaller than an equivalent JPG/PNG at the same visual quality',
                'Convert your JPG/PNG images to WebP — most image tools and CDNs support this in one step',
                'Keep a JPG/PNG <img> fallback via <picture> if you need to support very old browsers',
              ],
            },
            {
              slug: 'lazy-loading-images',
              label: 'Lazy-loaded images',
              prompt: 'Checked by rule engine (DOM parse for loading="lazy").',
              order: 6,
              weight: 1,
              fixable: true,
              fixType: 'patch',
            },
          ],
        },
        {
          slug: 'core-web-vitals',
          label: 'Core Web Vitals',
          order: 2,
          items: [
            {
              slug: 'core-web-vitals',
              label: 'Core Web Vitals',
              prompt: 'Checked by rule engine (Google Lighthouse performance audit).',
              order: 1,
              weight: 3,
              fixGuide: [
                'LCP (Largest Contentful Paint) measures how fast your main content appears — aim for under 2.5s',
                'TBT (Total Blocking Time) measures how long the page is unresponsive to input — aim for under 200ms',
                'CLS (Cumulative Layout Shift) measures visual stability — aim for under 0.1, usually fixed by setting explicit width/height on images and ads',
                'The checker below re-checks your live page automatically, so you can see the updated numbers right after you make a change',
              ],
            },
          ],
        },
      ],
    },

    // ── 4. Mobile Friendliness ────────────────────────────────────────────────
    {
      slug: 'mobile',
      label: 'Mobile Friendliness',
      order: 4,
      subCategories: [
        {
          slug: 'mobile-checks',
          label: 'Mobile Compatibility',
          order: 1,
          items: [
            {
              slug: 'viewport-configured',
              label: 'Mobile viewport configuration',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 3,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'no-fixed-width',
              label: 'Horizontal overflow on mobile',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
            },
            {
              slug: 'has-media-queries',
              label: 'Responsive layout',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 1,
            },
          ],
        },
        {
          slug: 'touch-checks',
          label: 'Touch & Interaction',
          order: 2,
          items: [
            {
              slug: 'hover-only-interactions',
              label: 'Hover-only interactions',
              prompt: 'Checked by rule engine (CSS rule parse for :hover without :focus).',
              order: 1,
              weight: 2,
              fixGuide: [
                'Any interaction that only triggers on :hover breaks completely on touchscreens — there is no hover state on mobile',
                'Add a matching :focus (or :focus-visible) rule alongside every meaningful :hover rule so keyboard and touch users get the same behavior',
                'Dropdown menus and tooltips are the most common offenders — make sure they also open on tap/focus',
              ],
            },
            {
              slug: 'safe-area-notch',
              label: 'Safe-area / notch handling',
              prompt: 'Checked by rule engine (CSS rule parse for env(safe-area-inset-*)).',
              order: 2,
              weight: 1,
              fixGuide: [
                'Only relevant if you have fixed-position headers, footers, or nav bars on mobile web',
                'Add padding using env(safe-area-inset-*) so content is not hidden behind notches or the home indicator',
                'Example: padding-bottom: env(safe-area-inset-bottom);',
              ],
            },
          ],
        },
        {
          slug: 'touch-checks-advanced',
          label: 'Touch & Layout (Browser-tested)',
          order: 3,
          items: [
            {
              slug: 'cursor-affordance',
              label: 'Cursor affordance',
              prompt: 'Checked by real browser interaction (computed cursor style).',
              order: 1,
              weight: 1,
              fixGuide: [
                'Any element with a click handler that isn\'t a native <a> or <button> needs cursor: pointer',
                'This is a small but real signal to sighted mouse users that something is clickable',
              ],
            },
            {
              slug: 'horizontal-scroll-mobile',
              label: 'Horizontal scroll on mobile',
              prompt: 'Checked by real browser rendering at 320-375px viewport widths.',
              order: 2,
              weight: 3,
              fixGuide: [
                'Load the page at a 320-375px viewport and check for a horizontal scrollbar',
                'The usual culprits: a fixed px width, an un-wrapped long word/URL, or a table without overflow-x: auto',
                'Constrain the offending element to max-width: 100% or wrap it in a scrollable container',
              ],
            },
            {
              slug: 'breakpoint-coverage',
              label: 'Breakpoint coverage (320-1440px)',
              prompt: 'Checked by real browser rendering across 320, 375, 768, 1024, and 1440px viewport widths.',
              order: 3,
              weight: 2,
              fixGuide: [
                'Test your page at each of 320, 375, 768, 1024, and 1440px in DevTools responsive mode',
                'Fix any width where content overflows or elements overlap',
                'Prefer flexible units (%, fr, minmax()) and flex-wrap over fixed pixel widths so the layout adapts naturally',
              ],
            },
          ],
        },
      ],
    },

    // ── 5. Trust Signals ──────────────────────────────────────────────────────
    {
      slug: 'trust',
      label: 'Trust Signals',
      order: 5,
      subCategories: [
        {
          slug: 'trust-checks',
          label: 'Security & Trust',
          order: 1,
          items: [
            {
              slug: 'uses-https',
              label: 'HTTPS',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 3,
            },
            {
              slug: 'ssl-valid',
              label: 'SSL certificate validity',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 3,
            },
            {
              slug: 'security-headers',
              label: 'Security response headers',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 2,
            },
            {
              slug: 'has-privacy-page',
              label: 'Privacy policy link',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 2,
              fixable: true,
              fixType: 'patch',
              partialFix: 'Adds a Privacy Policy link to your footer. Your /privacy-policy page must already exist — the agent cannot create the page content.',
            },
            {
              slug: 'has-contact-page',
              label: 'Contact page link',
              prompt: 'Checked by rule engine.',
              order: 5,
              weight: 1,
              fixable: true,
              fixType: 'patch',
              partialFix: 'Adds a Contact link to your footer. Your /contact page must already exist — the agent cannot create the page content.',
            },
          ],
        },
        {
          slug: 'trust-checks-advanced',
          label: 'Trust & Credibility (Visual)',
          order: 2,
          items: [
            {
              slug: 'trust-badges-placement',
              label: 'Trust signal placement',
              prompt: 'AI-assessed (vision): are trust signals visible near key conversion points?',
              order: 1,
              weight: 2,
              fixGuide: [
                'Place trust signals (reviews, ratings, security badges, customer logos) near your CTAs and forms, not buried in the footer',
                'Visitors decide whether to trust you in the same glance they decide whether to act — proximity matters',
              ],
            },
            {
              slug: 'brand-consistency',
              label: 'Cross-page brand consistency',
              prompt: 'AI-assessed (vision): is branding (logo, colors, typography) consistent across pages?',
              order: 2,
              weight: 1,
              fixGuide: [
                'Use the same logo, color palette, and font pairing across every page — inconsistency reads as unpolished or untrustworthy',
                'This is especially common to slip on landing pages built separately from the main site',
              ],
            },
          ],
        },
      ],
    },

    // ── 6. Conversion (CRO) ───────────────────────────────────────────────────
    {
      slug: 'cro',
      label: 'Conversion (CRO)',
      order: 6,
      subCategories: [
        {
          slug: 'cro-checks',
          label: 'Calls to Action',
          order: 1,
          items: [
            {
              slug: 'has-cta',
              label: 'Call-to-action',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 3,
            },
            {
              slug: 'cta-action-language',
              label: 'CTA button language',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
            },
            {
              slug: 'above-fold-cta',
              label: 'Above-fold call-to-action',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 2,
            },
            {
              slug: 'social-proof',
              label: 'Social proof signals',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 3,
            },
          ],
        },
      ],
    },

    // ── 7. Forms & CTAs ───────────────────────────────────────────────────────
    {
      slug: 'forms',
      label: 'Forms & CTAs',
      order: 7,
      subCategories: [
        {
          slug: 'forms-checks',
          label: 'Form Quality',
          order: 1,
          items: [
            {
              slug: 'form-labels',
              label: 'Form input labels',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 2,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'form-not-too-long',
              label: 'Form length',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
            },
            {
              slug: 'submit-button',
              label: 'Form submit button',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 3,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'placeholder-not-label',
              label: 'Form field labels vs placeholders',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 1,
            },
            {
              slug: 'required-field-indication',
              label: 'Required field indicators',
              prompt: 'Checked by rule engine (DOM parse for required attribute + visible indicator).',
              order: 5,
              weight: 1,
              fixGuide: [
                'Every field marked required in code should also be visibly marked in the UI',
                'Add an asterisk (*) or the word "required" next to the label of every required field',
                'This sets expectations before the user submits, instead of surprising them with an error',
              ],
            },
          ],
        },
        {
          slug: 'forms-checks-ai',
          label: 'Form Structure (AI)',
          order: 2,
          items: [
            {
              slug: 'progressive-disclosure',
              label: 'Multi-step form structure',
              prompt: 'AI-assessed: does a long form (>6 fields) use a multi-step/progressive pattern?',
              order: 1,
              weight: 1,
              fixGuide: [
                'Forms with more than 6-7 fields see meaningfully lower completion rates when shown all at once',
                'Break long forms into logical steps (e.g. "Step 1 of 3") so each screen feels short',
                'Show a progress indicator so users know how much is left',
              ],
            },
          ],
        },
        {
          slug: 'forms-checks-advanced',
          label: 'Forms (Browser-tested)',
          order: 3,
          items: [
            {
              slug: 'form-submit-error-handling',
              label: 'Form validation feedback',
              prompt: 'Checked by real browser interaction (submits the form empty and inspects the resulting DOM).',
              order: 1,
              weight: 2,
              fixGuide: [
                'Submit your own form with every field empty and confirm you see a clear error for each required field',
                'Use native HTML5 validation (required, type="email") or a visible custom error message — never fail silently',
                'Place the error right next to the field it refers to, not in a single generic banner at the top',
              ],
            },
            {
              slug: 'loading-disabled-submit-state',
              label: 'Submit button loading state',
              prompt: 'Checked by real browser interaction (button state immediately before/after a click).',
              order: 2,
              weight: 1,
              fixGuide: [
                'Disable the submit button (or show a spinner/loading label) the instant it\'s clicked',
                'This prevents duplicate submissions and reassures the user something is happening',
              ],
            },
          ],
        },
      ],
    },

    // ── 8. Technical Health ───────────────────────────────────────────────────
    {
      slug: 'tech',
      label: 'Technical Health',
      order: 8,
      subCategories: [
        {
          slug: 'tech-checks',
          label: 'Technical SEO & Metadata',
          order: 1,
          items: [
            {
              slug: 'meta-description',
              label: 'Meta description',
              prompt: 'Checked by rule engine.',
              order: 1,
              weight: 3,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'canonical',
              label: 'Canonical URL',
              prompt: 'Checked by rule engine.',
              order: 2,
              weight: 2,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'og-tags',
              label: 'Social sharing preview (Open Graph)',
              prompt: 'Checked by rule engine.',
              order: 3,
              weight: 2,
              fixable: true,
              fixType: 'patch',
              upgradeInput: {
                key: 'og_image_url',
                label: 'OG Image URL',
                placeholder: 'https://yourdomain.com/og-image.jpg',
                setupInstructions: 'Agent sets og:title and og:description from page content but cannot determine og:image. Save your OG image URL in Settings → Brand Assets to get a complete fix.',
              },
            },
            {
              slug: 'image-alt-text',
              label: 'Image alt text',
              prompt: 'Checked by rule engine.',
              order: 4,
              weight: 2,
            },
            {
              slug: 'robots-txt',
              label: 'robots.txt',
              prompt: 'Checked by rule engine.',
              order: 5,
              weight: 2,
              fixable: true,
            },
            {
              slug: 'sitemap-xml',
              label: 'sitemap.xml',
              prompt: 'Checked by rule engine.',
              order: 6,
              weight: 2,
              fixable: true,
              partialFix: 'Creates a skeleton sitemap.xml with your root URL only. Does not auto-discover other pages — extend it manually after the fix is applied.',
            },
            {
              slug: 'structured-data',
              label: 'Rich results markup (JSON-LD)',
              prompt: 'Checked by rule engine.',
              order: 7,
              weight: 1,
              fixable: true,
              fixType: 'patch',
              upgradeInput: {
                key: 'logo_url',
                label: 'Logo URL',
                placeholder: 'https://yourdomain.com/logo.png',
                setupInstructions: 'Agent creates a basic Organisation schema with name and URL but cannot determine your logo. Save your logo URL in Settings → Brand Assets to include it in the JSON-LD.',
              },
            },
            {
              slug: 'lang-attr',
              label: 'HTML language attribute',
              prompt: 'Checked by rule engine.',
              order: 8,
              weight: 2,
              fixable: true,
              fixType: 'patch',
            },
            {
              slug: 'alt-text-quality',
              label: 'Alt text quality',
              prompt: 'AI-assessed: are alt texts descriptive, or generic/keyword-stuffed/same-as-filename?',
              order: 9,
              weight: 2,
              fixGuide: [
                'Alt text should describe what\'s in the image and why it matters in context, not just repeat the filename or stuff in keywords',
                'Bad: alt="IMG_2024.jpg" or alt="team photo photo team business". Good: alt="Our 12-person team at the 2024 all-hands"',
                'Decorative images that add no information should use alt="" so screen readers skip them',
              ],
            },
          ],
        },
      ],
    },

    // ── 9. Content & Clarity ──────────────────────────────────────────────────
    {
      slug: 'content',
      label: 'Content & Clarity',
      order: 9,
      subCategories: [
        {
          slug: 'content-checks',
          label: 'Copy Quality (AI)',
          order: 1,
          items: [
            {
              slug: 'copy-scannability',
              label: 'Copy scannability',
              prompt: 'AI-assessed: is body copy broken into scannable chunks or a dense wall of text?',
              order: 1,
              weight: 2,
              fixGuide: [
                'Most visitors scan a page before they read it — dense paragraphs get skipped entirely',
                'Break long paragraphs into 2-3 sentence chunks with a clear heading or subheading every few paragraphs',
                'Use bullet points for lists of features/benefits instead of burying them in a paragraph',
              ],
            },
            {
              slug: 'jargon-language',
              label: 'Jargon vs. plain language',
              prompt: 'AI-assessed: is copy written in plain, audience-appropriate language or full of unexplained jargon?',
              order: 2,
              weight: 2,
              fixGuide: [
                'Unexplained jargon and buzzwords force visitors to work harder to understand what you do',
                'Rewrite key sections in plain language a first-time visitor with no industry background would understand',
                'If a technical term is necessary for your audience, define it briefly the first time it appears',
              ],
            },
            {
              slug: '404-page-quality',
              label: '404 page quality',
              prompt: 'AI-assessed: does the site have a helpful, on-brand 404 page, or a generic/broken one?',
              order: 3,
              weight: 2,
              fixGuide: [
                'A good 404 page explains what happened in plain language and offers a clear way back (search, nav links, or a link home)',
                'Match your site\'s branding and tone — a generic server error page feels broken and erodes trust',
                'Consider linking to your most popular pages or search from the 404 page to recover the lost visit',
              ],
            },
          ],
        },
        {
          slug: 'content-checks-advanced',
          label: 'Content & Clarity (Browser-tested)',
          order: 2,
          items: [
            {
              slug: 'empty-state-quality',
              label: 'Empty-state design',
              prompt: 'AI-assessed (vision): if the page has search, does a no-results search show a helpful empty state?',
              order: 1,
              weight: 1,
              fixGuide: [
                'A no-results state should explain what happened and suggest a next step (broaden the search, browse categories, contact support)',
                'Avoid a blank page or a bare "No results found" with nothing else — it\'s a dead end for the visitor',
                'Only applies if your page has a search feature — this check reports "info" if none was found',
              ],
            },
          ],
        },
      ],
    },

    // ── 10. Visual Hierarchy & Clarity ────────────────────────────────────────
    {
      slug: 'visual-hierarchy',
      label: 'Visual Hierarchy & Clarity',
      order: 10,
      subCategories: [
        {
          slug: 'visual-hierarchy-checks',
          label: 'Visual Review (AI)',
          order: 1,
          description: 'Font size/line-height readability is already covered under Accessibility & WCAG.',
          items: [
            {
              slug: 'hero-cta-prominence',
              label: 'Above-the-fold CTA prominence',
              prompt: 'AI-assessed (vision): is there one clear, prominent primary CTA above the fold?',
              order: 1,
              weight: 3,
              fixGuide: [
                'Your primary action (start trial, book a demo, buy) should be the single most visually prominent element in the hero',
                'Use size, color contrast, and whitespace around the button to make it impossible to miss',
                'If there are secondary actions, style them visibly weaker (outline/text button) so they don\'t compete',
              ],
            },
            {
              slug: 'competing-ctas',
              label: 'Competing CTAs',
              prompt: 'AI-assessed (vision): are multiple CTAs competing for attention with similar visual weight?',
              order: 2,
              weight: 2,
              fixGuide: [
                'Every screen should have one clear primary action — everything else should look secondary',
                'If you truly need two CTAs above the fold, give them clearly different visual weight (solid vs. outline button)',
              ],
            },
            {
              slug: 'icon-consistency',
              label: 'Icon consistency',
              prompt: 'AI-assessed (vision): are icons consistent in style, stroke width, and sizing?',
              order: 3,
              weight: 1,
              fixGuide: [
                'Pick one icon set/style (line vs. filled, stroke width) and use it everywhere — mixing icon libraries is a common visual tell of a rushed build',
                'Keep icon sizes consistent within the same context (e.g. all nav icons the same size)',
              ],
            },
            {
              slug: 'whitespace-rhythm',
              label: 'Whitespace rhythm',
              prompt: 'AI-assessed (vision): does the layout have a consistent, breathable spacing rhythm?',
              order: 4,
              weight: 1,
              fixGuide: [
                'Use a consistent spacing scale (e.g. 8px increments) for margins and padding across sections',
                'Cramped or wildly inconsistent spacing between sections reads as unpolished even if the copy and colors are good',
              ],
            },
            {
              slug: 'text-legibility-busy-bg',
              label: 'Text over busy backgrounds',
              prompt: 'AI-assessed (vision): is any text hard to read over a photo/gradient/busy background?',
              order: 5,
              weight: 2,
              fixGuide: [
                'Add a solid or gradient overlay behind text placed on a photo, so contrast holds regardless of the image underneath',
                'This is a common failure point in hero sections with a background image — test with several different real images, not just the one that looked good in the mockup',
              ],
            },
            {
              slug: 'color-not-only-indicator',
              label: 'Color-only status indicators',
              prompt: 'AI-assessed (vision): is any status/state shown only via color, with no icon or text?',
              order: 6,
              weight: 2,
              fixGuide: [
                'Never use color alone to convey status (e.g. a red vs. green dot) — about 1 in 12 men have some form of color vision deficiency',
                'Pair color with an icon, label, or pattern so the state is clear without relying on color perception',
              ],
            },
          ],
        },
      ],
    },
  ],
}
