import {
  pgTable, uuid, integer, timestamp, unique,
  text, boolean, jsonb, type AnyPgColumn,
} from 'drizzle-orm/pg-core'

// ── Brands ───────────────────────────────────────────────────────────────────

export const brands = pgTable('brands', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull(),
  name: text('name').notNull(),
  websiteUrl: text('website_url').notNull(),
  keywords: text('keywords'), // comma-separated brand keywords/tags
  industry: text('industry'),
  targetAudience: text('target_audience'),
  usp: text('usp'),
  brandVoice: text('brand_voice'),
  logoUrl: text('logo_url'),
  themeColor: text('theme_color'),
  playbook: jsonb('playbook'),   // PlaybookData — generated by Foundation analysis, editable by user
  analyticsSnapshot: jsonb('analytics_snapshot'),         // cached /api/analytics/auth-dashboard response
  analyticsSnapshotAt: timestamp('analytics_snapshot_at', { withTimezone: true }), // when cache was last saved
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
})

// ── Competitor Registry (centralized across all modules) ──────────────────

export const competitors = pgTable(
  'competitors',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
    url: text('url').notNull(),
    name: text('name'), // e.g. "Buffer", "Hootsuite"
    type: text('type'), // 'direct' | 'indirect' | 'aspirational' — competitor classification
    marketPosition: text('market_position'), // 'leader' | 'challenger' | 'niche_player' | 'new_entrant'
    primaryStrength: text('primary_strength'), // main competitive advantage observed
    discoveredIn: text('discovered_in'), // module type that discovered it (e.g. 'competitor-analysis')
    discoveredAt: timestamp('discovered_at', { withTimezone: true }).defaultNow(),
    lastAnalyzedAt: timestamp('last_analyzed_at', { withTimezone: true }),
  },
  (table) => ({
    uniq: unique('competitors_unique').on(table.brandId, table.url),
  }),
)

// ── Modules ──────────────────────────────────────────────────────────────────

export const modules = pgTable('modules', {
  id: uuid('id').primaryKey().defaultRandom(),
  brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
  type: text('type').notNull(),           // 'foundation' | 'seo' | 'social_media' | ...
  name: text('name').notNull(),
  order: integer('order').notNull(),      // 0 = Foundation, 1 = SEO, 2 = Social, ...
  status: text('status').notNull().default('locked'), // 'locked'|'pending'|'analyzing'|'complete'
  requirements: jsonb('requirements'),    // { website_url: "https://..." }
  score: integer('score').default(0),     // 0-100 completion %
  lastAnalyzedAt: timestamp('last_analyzed_at', { withTimezone: true }),
  agentBranch: text('agent_branch'),      // shared GitHub branch for this module's fixes
  agentPrUrl: text('agent_pr_url'),       // GitHub PR URL for the shared fixes branch
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
})

// ── Module Categories (self-referential for sub-categories) ──────────────────

export const moduleCategories = pgTable('module_categories', {
  id: uuid('id').primaryKey().defaultRandom(),
  moduleId: uuid('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
  parentId: uuid('parent_id').references((): AnyPgColumn => moduleCategories.id, { onDelete: 'cascade' }),
  slug: text('slug').notNull(),
  label: text('label').notNull(),
  order: integer('order').notNull(),
})

// ── Module Items (actionable checklist items) ─────────────────────────────────

export const moduleItems = pgTable(
  'module_items',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    moduleId: uuid('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
    categoryId: uuid('category_id').notNull().references(() => moduleCategories.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    label: text('label').notNull(),
    weight: integer('weight').notNull().default(1), // 1=minor | 2=important | 3=critical
    aiDetail: text('ai_detail'),           // one-line finding (always shown)
    aiHighlight: text('ai_highlight'),     // 5–8 word key phrase (shown expanded, prominent)
    aiNarrative: text('ai_narrative'),     // 1-sentence context (expandable)
    aiAction: text('ai_action'),           // specific next step (expandable)
    aiVerified: boolean('ai_verified').default(false),
    aiVerifiedAt: timestamp('ai_verified_at', { withTimezone: true }),
    userChecked: boolean('user_checked').default(false),
    userCheckedAt: timestamp('user_checked_at', { withTimezone: true }),
    completedBy: text('completed_by'),     // 'ai' | 'user' | 'agent' | null
    fixable: boolean('fixable').default(false), // true = Claude can auto-fix via GitHub
    fixType: text('fix_type'),                             // 'template' | 'value' | 'patch' | null (null = legacy full-file flow)
    fixInputKey: text('fix_input_key'),                    // metadata key to read from brandIntegrations (e.g. 'ga4_measurement_id')
    fixIntegrationProvider: text('fix_integration_provider'), // which integration to read from (e.g. 'google_analytics')
    aiDraft: text('ai_draft'),             // on-demand AI-generated draft content (copy, outline, template)
    aiData: jsonb('ai_data'),              // structured data payload (e.g. calendar entries JSON for content-calendar-30-day)
    userSkipped: boolean('user_skipped').default(false),
    userSkipReason: text('user_skip_reason'),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    uniq: unique('module_item_unique').on(table.moduleId, table.slug),
  }),
)

// ── Brand Integrations ────────────────────────────────────────────────────────

export const brandIntegrations = pgTable(
  'brand_integrations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),        // 'github' | 'openai' | 'vercel' | ...
    type: text('type').notNull(),                // 'oauth' | 'api_key' | 'webhook'
    status: text('status').notNull().default('connected'), // 'connected' | 'expired' | 'revoked'
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    tokenExpiresAt: timestamp('token_expires_at', { withTimezone: true }),
    scopes: text('scopes').array(),
    apiKey: text('api_key'),
    metadata: jsonb('metadata'),                 // { repo_url, default_branch, stack_type, ... }
    connectedAt: timestamp('connected_at', { withTimezone: true }).defaultNow(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  },
  (table) => ({
    uniq: unique('brand_integration_unique').on(table.brandId, table.provider),
  }),
)

// ── Brain Agent ───────────────────────────────────────────────────────────────

export const brainContext = pgTable('brain_context', {
  id: uuid('id').primaryKey().defaultRandom(),
  brandId: uuid('brand_id').notNull().unique().references(() => brands.id, { onDelete: 'cascade' }),
  summary: text('summary'),                 // running narrative of brand health
  facts: jsonb('facts'),                    // { foundation: {...}, seo: {...} } — accumulated per module
  userResolved: jsonb('user_resolved'),     // string[] — slugs user self-reported as fixed
  priorityQueue: jsonb('priority_queue'),
  lastUpdated: timestamp('last_updated', { withTimezone: true }).defaultNow(),
})

export const itemLinks = pgTable('item_links', {
  id: uuid('id').primaryKey().defaultRandom(),
  itemIdA: uuid('item_id_a').notNull().references(() => moduleItems.id, { onDelete: 'cascade' }),
  itemIdB: uuid('item_id_b').notNull().references(() => moduleItems.id, { onDelete: 'cascade' }),
  relationshipType: text('relationship_type').notNull(), // 'same_issue'|'related'|'depends_on'
  createdBy: text('created_by').notNull(),               // 'ai' | 'hardcoded'
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
})

export const brainInsights = pgTable('brain_insights', {
  id: uuid('id').primaryKey().defaultRandom(),
  brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
  insight: text('insight').notNull(),
  affectedItemIds: uuid('affected_item_ids').array(),
  impactScore: integer('impact_score').default(0),
  resolved: boolean('resolved').default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
})

// ── Module Page Audit (content audit per-page verdicts) ───────────────────────

export const modulePageAudit = pgTable(
  'module_page_audit',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    moduleId: uuid('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
    url: text('url').notNull(),
    title: text('title'),
    wordCount: integer('word_count').default(0),
    verdict: text('verdict').notNull(),   // 'Keep' | 'Refresh' | 'Consolidate' | 'Repurpose' | 'Remove'
    urgency: text('urgency').notNull(),   // 'High' | 'Medium' | 'Low'
    reason: text('reason'),
    action: text('action'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    uniq: unique('module_page_audit_unique').on(table.moduleId, table.url),
  }),
)

// ── Community Finder Module ───────────────────────────────────────────────────

export const communities = pgTable(
  'communities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
    moduleId: uuid('module_id').notNull().references(() => modules.id, { onDelete: 'cascade' }),
    platform: text('platform').notNull(), // 'facebook' | 'linkedin'
    platformId: text('platform_id').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    link: text('link').notNull(),
    memberCount: integer('member_count'),
    activityScore: integer('activity_score'), // 0-100
    relevanceScore: integer('relevance_score'), // 0-100
    competitorPresence: boolean('competitor_presence').default(false),
    healthScore: integer('health_score'), // 0-100
    lastAnalyzedAt: timestamp('last_analyzed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    uniq: unique('communities_unique').on(table.brandId, table.platform, table.platformId),
  }),
)

export const communityAnalysis = pgTable(
  'community_analysis',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    communityId: uuid('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
    sentimentPositive: integer('sentiment_positive'), // percentage
    sentimentNeutral: integer('sentiment_neutral'),
    sentimentNegative: integer('sentiment_negative'),
    painPoints: jsonb('pain_points'), // [{pain: string, frequency: number}]
    cultureSummary: text('culture_summary'),
    topPosts: jsonb('top_posts'), // [{title: string, engagement: number}]
    analyzedAt: timestamp('analyzed_at', { withTimezone: true }).defaultNow(),
  },
)

export const engagementStrategy = pgTable(
  'engagement_strategy',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    communityId: uuid('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
    conversationStarters: jsonb('conversation_starters'), // string[]
    valuePosts: jsonb('value_posts'), // string[]
    softPitches: jsonb('soft_pitches'), // string[]
    optimalTimes: jsonb('optimal_times'), // [{day: string, time: string}]
    replyStrategy: text('reply_strategy'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
)

export const communityPerformance = pgTable(
  'community_performance',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    communityId: uuid('community_id').notNull().references(() => communities.id, { onDelete: 'cascade' }),
    date: text('date').notNull(), // YYYY-MM-DD
    postsShared: integer('posts_shared').default(0),
    commentsReceived: integer('comments_received').default(0),
    reactionsReceived: integer('reactions_received').default(0),
    sharesReceived: integer('shares_received').default(0),
    repliesPosted: integer('replies_posted').default(0),
    websiteVisits: integer('website_visits').default(0),
    trialSignups: integer('trial_signups').default(0),
    sentimentScore: integer('sentiment_score'), // 0-100
    engagementRate: integer('engagement_rate'), // percentage
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    uniq: unique('community_performance_unique').on(table.communityId, table.date),
  }),
)

// ── Frekto Scheduled Posts ────────────────────────────────────────────────────

export const frektoScheduledPosts = pgTable('frekto_scheduled_posts', {
  id: uuid('id').primaryKey().defaultRandom(),
  brandId: uuid('brand_id').notNull().references(() => brands.id, { onDelete: 'cascade' }),
  platform: text('platform').notNull(),      // 'instagram' | 'linkedin' | 'twitter' | 'facebook' | 'youtube' | 'tiktok'
  topic: text('topic').notNull(),
  postType: text('post_type').notNull(),     // 'image' | 'video'
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(),
  frektoJobId: text('frekto_job_id'),
  outputUrl: text('output_url'),
  status: text('status').notNull().default('scheduled'), // 'scheduled' | 'done' | 'failed'
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})

// ── Features ──────────────────────────────────────────────────────────────────

export const features = pgTable(
  'features',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
    description: text('description'),
    keywords: text('keywords'), // comma-separated keywords to search for in commits
    isCompleted: boolean('is_completed').default(false),
    completedAt: timestamp('completed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
)
