// ── Static module types (Foundation — items hardcoded in definition) ──────────

export type FixType =
  | 'template'  // head tag, no AI — cheerio applies a known tag/value directly
  | 'value'     // head tag, tiny AI call returns the string only — cheerio applies it
  | 'patch'     // body tag, full file sent to Claude — Claude returns find/replace pair only, cheerio applies

export interface ModuleItemDefinition {
  slug: string
  label: string
  prompt: string
  order: number
  weight: 1 | 2 | 3
  fixGuide?: string[]  // static step-by-step instructions shown in expanded item body (handoff doc)
  fixable?: boolean  // true = this item can be auto-fixed via GitHub
  fixType?: FixType  // controls which fix path is used (undefined = legacy full-file Claude flow)
  assistedInput?: {  // fix is BLOCKED until user saves this value in an integration
    key: string                 // metadata key stored in brandIntegrations e.g. 'ga4_measurement_id'
    integrationProvider: string // provider slug e.g. 'google_analytics'
    setupInstructions: string   // tooltip: what user needs to do before fix can run
  }
  upgradeInput?: {   // fix runs now (partial), becomes complete once user saves this in Brand Assets
    key: string              // metadata key in brandIntegrations 'brand_assets' e.g. 'og_image_url'
    label: string            // human label e.g. "OG Image URL"
    placeholder: string      // e.g. "https://yourdomain.com/og-image.jpg"
    setupInstructions: string // tooltip explaining what to save and where
  }
  partialFix?: string  // fix always runs but is inherently incomplete — this string explains the gap
}

export interface ModuleSubCategoryDefinition {
  slug: string
  label: string
  order: number
  description?: string   // optional info notice shown at the top of the sub-category
  requires?: string[]    // integration provider slugs needed for full functionality (e.g. ['gsc_api', 'serpapi'])
  items: ModuleItemDefinition[]
}

export interface ModuleCategoryDefinition {
  slug: string
  label: string
  order: number
  description?: string   // optional info shown inside the category when expanded
  subCategories: ModuleSubCategoryDefinition[]
}

// ── Dynamic module types (SEO, Social, etc. — items generated by Claude) ──────

// Category definition for dynamic modules: just a slug, label, and prompt
// Claude decides which items to create based on what it actually finds
export interface DynamicModuleCategoryDefinition {
  slug: string
  label: string
  order: number
  prompt: string   // instructions for Claude for this category
  comingSoon?: boolean   // true = show Coming Soon block instead of items
  comingSoonNote?: string  // optional description shown in the Coming Soon block
}

// Type guard
export function isDynamicCategory(
  cat: ModuleCategoryDefinition | DynamicModuleCategoryDefinition,
): cat is DynamicModuleCategoryDefinition {
  return 'prompt' in cat
}

// ── Requirement a module needs from the user before it can be analysed ────────

export interface ModuleRequirement {
  key: string
  label: string
  type: 'url' | 'text' | 'url_list' | 'text_list'
  placeholder?: string
  required?: boolean  // defaults to true if not specified
}

// ── The full definition every module must export ──────────────────────────────

export interface ModuleDefinition {
  type: string
  name: string
  tagline?: string
  description: string
  order: number
  unlockThreshold: number
  dynamic?: boolean   // true = Claude generates items; false/undefined = items hardcoded
  comingSoon?: boolean     // true = entire module shows Coming Soon state
  comingSoonNote?: string  // optional description shown in the module-level Coming Soon block
  requirements: ModuleRequirement[]
  categories: (ModuleCategoryDefinition | DynamicModuleCategoryDefinition)[]
  systemPrompt: string
}

// ── Analysis result — static modules (Claude fills in findings per pre-seeded item) ──

export interface ModuleAnalysisResult {
  slug: string
  detail: string
  highlight?: string
  narrative: string
  action: string
  verified: boolean
}

// ── Analysis result — dynamic modules (Claude generates the items themselves) ──

export interface DynamicModuleAnalysisResult {
  category: string      // category slug — which section this item belongs to
  slug: string          // kebab-case, stable across re-runs for the same issue
  label: string         // short checklist label, specific to what was found
  weight: 1 | 2 | 3    // 3=critical | 2=important | 1=minor
  detail: string        // one-sentence finding
  highlight?: string    // 5–8 word key phrase (shown prominently when expanded)
  narrative: string     // 1-sentence context explanation
  action: string        // specific next step, verb-first
  verified: boolean     // true = passes | false = needs attention
  fixable: boolean      // true = safe to auto-fix via GitHub (meta/title/canonical/OG tags only)
  fixType?: FixType     // controls which fix path is used
}

// ── Full item row passed to dashboard for dynamic modules ─────────────────────

export interface DBItemFull {
  id: string
  slug: string
  label: string
  weight: number
  categorySlug: string
  aiDetail: string | null
  aiHighlight: string | null
  aiNarrative: string | null
  aiAction: string | null
  aiDraft: string | null
  aiData: unknown | null   // structured payload e.g. CalendarEntry[] for content-calendar-30-day
  aiVerified: boolean
  userChecked: boolean
  completedBy: string | null
  fixable: boolean
  fixType: FixType | null
  fixInputKey: string | null
  fixIntegrationProvider: string | null
  userSkipped: boolean
  userSkipReason: string | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getAllItems(mod: ModuleDefinition): ModuleItemDefinition[] {
  if (mod.dynamic) return []
  return (mod.categories as ModuleCategoryDefinition[]).flatMap((cat) =>
    cat.subCategories.flatMap((sub) => sub.items),
  )
}

export function getTotalWeight(mod: ModuleDefinition): number {
  return getAllItems(mod).reduce((sum, i) => sum + i.weight, 0)
}
