// ── Static module types (Foundation — items hardcoded in definition) ──────────

export interface ModuleItemDefinition {
  slug: string
  label: string
  prompt: string
  order: number
  weight: 1 | 2 | 3
  fixable?: boolean  // true = this item can be auto-fixed via GitHub
  assistedInput?: {  // if set, user must save this value in Settings → Integrations first
    key: string                 // metadata key stored in brandIntegrations e.g. 'ga4_measurement_id'
    integrationProvider: string // provider slug e.g. 'google_analytics'
    setupInstructions: string   // tooltip: what user needs to do before fix can run
  }
}

export interface ModuleSubCategoryDefinition {
  slug: string
  label: string
  order: number
  items: ModuleItemDefinition[]
}

export interface ModuleCategoryDefinition {
  slug: string
  label: string
  order: number
  subCategories: ModuleSubCategoryDefinition[]
}

// ── Dynamic module types (SEO, Social, etc. — items generated by Claude) ──────

// Category definition for dynamic modules: just a slug, label, and prompt
// Claude decides which items to create based on what it actually finds
export interface DynamicModuleCategoryDefinition {
  slug: string
  label: string
  order: number
  prompt: string   // instructions for Claude for this category
}

// Type guard
export function isDynamicCategory(
  cat: ModuleCategoryDefinition | DynamicModuleCategoryDefinition,
): cat is DynamicModuleCategoryDefinition {
  return 'prompt' in cat
}

// ── Requirement a module needs from the user before it can be analysed ────────

export interface ModuleRequirement {
  key: string
  label: string
  type: 'url' | 'text' | 'url_list' | 'text_list'
  placeholder?: string
  required?: boolean  // defaults to true if not specified
}

// ── The full definition every module must export ──────────────────────────────

export interface ModuleDefinition {
  type: string
  name: string
  description: string
  order: number
  unlockThreshold: number
  dynamic?: boolean   // true = Claude generates items; false/undefined = items hardcoded
  requirements: ModuleRequirement[]
  categories: (ModuleCategoryDefinition | DynamicModuleCategoryDefinition)[]
  systemPrompt: string
}

// ── Analysis result — static modules (Claude fills in findings per pre-seeded item) ──

export interface ModuleAnalysisResult {
  slug: string
  detail: string
  narrative: string
  action: string
  verified: boolean
}

// ── Analysis result — dynamic modules (Claude generates the items themselves) ──

export interface DynamicModuleAnalysisResult {
  category: string      // category slug — which section this item belongs to
  slug: string          // kebab-case, stable across re-runs for the same issue
  label: string         // short checklist label, specific to what was found
  weight: 1 | 2 | 3    // 3=critical | 2=important | 1=minor
  detail: string        // one-sentence finding
  narrative: string     // 2–3 sentence explanation
  action: string        // specific next step
  verified: boolean     // true = passes | false = needs attention
  fixable: boolean      // true = safe to auto-fix via GitHub (meta/title/canonical/OG tags only)
}

// ── Full item row passed to dashboard for dynamic modules ─────────────────────

export interface DBItemFull {
  id: string
  slug: string
  label: string
  weight: number
  categorySlug: string
  aiDetail: string | null
  aiNarrative: string | null
  aiAction: string | null
  aiVerified: boolean
  userChecked: boolean
  completedBy: string | null
  fixable: boolean
  fixInputKey: string | null
  fixIntegrationProvider: string | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getAllItems(mod: ModuleDefinition): ModuleItemDefinition[] {
  if (mod.dynamic) return []
  return (mod.categories as ModuleCategoryDefinition[]).flatMap((cat) =>
    cat.subCategories.flatMap((sub) => sub.items),
  )
}

export function getTotalWeight(mod: ModuleDefinition): number {
  return getAllItems(mod).reduce((sum, i) => sum + i.weight, 0)
}
